version: '3'
services: 
    test-memory-22:
        build: 
            dockerfile: ./docker/22.dockerfile
            context: ../
        image: test-memory-22
        container_name: c-test-memory-22
        ports: 
            - '5000:80'

    test-memory-30:
        build: 
            dockerfile: ./docker/30.dockerfile
            context: ../
        image: test-memory-30
        container_name: c-test-memory-30
        ports: 
            - '5003:80'